% this script plots the mean profiles generated by HERCULES

clear all;
clc

% grid numbers
nx=256;
ny=192;
nz=128;

% read MKM99
MKM99a=load('MKM99.chan180.means');
MKM99b=load('MKM99.reystress');

% input path
inpath=['../../results/'];

% read mean fields generated by HERCULES
fid1=fopen([inpath 'mean_u.dat'],'r');
fid2=fopen([inpath 'mean_v.dat'],'r');
fid3=fopen([inpath 'mean_w.dat'],'r');
fid4=fopen([inpath 'mean_uu.dat'],'r');
fid5=fopen([inpath 'mean_vv.dat'],'r');
fid6=fopen([inpath 'mean_ww.dat'],'r');
fid7=fopen([inpath 'mean_uw.dat'],'r');

umean=fread(fid1,nx*ny*nz,'float64');
vmean=fread(fid2,nx*ny*nz,'float64');
wmean=fread(fid3,nx*ny*nz,'float64');
uu=fread(fid4,nx*ny*nz,'float64');
vv=fread(fid5,nx*ny*nz,'float64');
ww=fread(fid6,nx*ny*nz,'float64');
uw=fread(fid7,nx*ny*nz,'float64');

% read z
geo=load([inpath 'geo.info']);
z=geo(:,1);

% reshape
umean3D=reshape(umean,nx,ny,nz);
vmean3D=reshape(vmean,nx,ny,nz);
wmean3D=reshape(wmean,nx,ny,nz);
uu3D=reshape(uu,nx,ny,nz);
vv3D=reshape(vv,nx,ny,nz);
ww3D=reshape(ww,nx,ny,nz);
uw3D=reshape(uw,nx,ny,nz);

% since uu=<u*u>, we need to transfer it to <(u-<u>)^2>
uu3D=uu3D-umean3D.^2.0;
vv3D=vv3D-vmean3D.^2.0;
ww3D=ww3D-wmean3D.^2.0;
uw3D=uw3D-umean3D.*wmean3D;

% do the mean
umean1=mean( squeeze(mean(umean3D,1)), 1);
vmean1=mean( squeeze(mean(vmean3D,1)), 1);
wmean1=mean( squeeze(mean(wmean3D,1)), 1);
uu1=mean( squeeze(mean(uu3D,1)), 1);
vv1=mean( squeeze(mean(vv3D,1)), 1);
ww1=mean( squeeze(mean(ww3D,1)), 1);
uw1=mean( squeeze(mean(uw3D,1)), 1);

% plot the results
figure(1)
plot(z,umean1,'-r',MKM99a(:,1),MKM99a(:,3),'ko');
set(gca,'xlim',[0 1])
title('U')

figure(2)
plot(z,uu1,'-r',MKM99b(:,1),MKM99b(:,3),'ko');
set(gca,'xlim',[0 1])
title('u_{rms}')

figure(3)
plot(z,-uw1,'-r',MKM99b(:,1),-MKM99b(:,6),'ko');
set(gca,'xlim',[0 1])
title('-uw')
  
     
return;
